import { useState } from "react";
import { useAdminWallets } from "@/frontend/hooks/useWallet";
import { RealtimeStatusIndicator } from "@/frontend/components/RealtimeStatusIndicator";
import { ResponsiveTable, type Column } from "@/frontend/components/ResponsiveTable";
import { cn } from "@/frontend/theme/tokens";
import { Users, Building2, Stethoscope, ShoppingBag, Wallet, Coins, AlertTriangle, Snowflake, Gift, Shield, Settings, Search, Eye, Ban, Loader2, ChevronRight, ArrowDownRight, ArrowUpRight } from "lucide-react";
import { formatBDT } from "@/frontend/utils/currency";
import { formatPoints, pointsToBDT, DEFAULT_PLATFORM_FEE_PERCENT, DEFAULT_COMMISSION_PERCENT } from "@/frontend/utils/points";
import type { WalletSummary } from "@/frontend/utils/points";
import { useTranslation } from "react-i18next";
import { useDocumentTitle } from "@/frontend/hooks";

type WalletEntry = WalletSummary;

const ROLE_CONFIG: Record<string, { icon: typeof Users; color: string; bg: string; label: string }> = {
  guardian: { icon: Users, color: "var(--cn-green)", bg: "var(--cn-green-bg)", label: "Guardian" },
  agency: { icon: Building2, color: "var(--cn-teal)", bg: "var(--cn-teal-bg)", label: "Agency" },
  caregiver: { icon: Stethoscope, color: "var(--cn-pink)", bg: "var(--cn-pink-bg)", label: "Caregiver" },
  shop: { icon: ShoppingBag, color: "var(--cn-orange)", bg: "var(--cn-orange-bg)", label: "Shop" },
};

export default function AdminWalletManagementPage() {
  const { t: tDocTitle } = useTranslation("common");
  useDocumentTitle(tDocTitle("pageTitles.adminWalletManagement", "Admin Wallet Management"));

  const [search, setSearch] = useState("");
  const [selectedWallet, setSelectedWallet] = useState<WalletEntry | null>(null);
  const [creditAmount, setCreditAmount] = useState("");
  const [creditReason, setCreditReason] = useState("");
  const [debitAmount, setDebitAmount] = useState("");
  const [debitReason, setDebitReason] = useState("");
  const [showCredit, setShowCredit] = useState(false);
  const [showDebit, setShowDebit] = useState(false);

  const { wallets: allWallets, loading, error, refetch, creditPoints, debitPoints, toggleFreeze, updateFeeConfig, getTransactions } = useAdminWallets();
  const [walletTxs, setWalletTxs] = useState<import("@/frontend/utils/points").PointTransaction[]>([]);

  const wallets = allWallets.filter((w) => w.userName.toLowerCase().includes(search.toLowerCase()) || w.userRole.toLowerCase().includes(search.toLowerCase()));
  const totalBalance = allWallets.reduce((s, w) => s + w.balance, 0);
  const totalDues = allWallets.reduce((s, w) => s + w.pendingDue, 0);
  const totalFrozen = allWallets.reduce((s, w) => s + w.frozenAmount, 0);
  const totalBonusGiven = allWallets.reduce((s, w) => s + w.registrationBonus, 0);

  if (loading && allWallets.length === 0) { return (<div className="flex flex-col items-center justify-center py-20"><Loader2 className="w-8 h-8 animate-spin mb-3" style={{ color: cn.pink }} /><p className="text-sm" style={{ color: cn.textSecondary }}>Loading wallets...</p></div>); }

  const handleSelectWallet = async (w: WalletEntry) => { setSelectedWallet(w); setShowCredit(false); setShowDebit(false); const txs = await getTransactions(w.userId, { limit: 5 }); setWalletTxs(txs); };
  const handleCreditSubmit = async () => { if (!selectedWallet || !creditAmount || !creditReason) return; const success = await creditPoints(selectedWallet.userId, parseInt(creditAmount), creditReason, creditReason); if (success) { setCreditAmount(""); setCreditReason(""); setShowCredit(false); } };
  const handleDebitSubmit = async (freeze: boolean) => { if (!selectedWallet || !debitAmount || !debitReason) return; const success = await debitPoints(selectedWallet.userId, parseInt(debitAmount), debitReason, debitReason, freeze); if (success) { setDebitAmount(""); setDebitReason(""); setShowDebit(false); } };
  const handleFreezeToggle = async () => { if (!selectedWallet) return; const freeze = selectedWallet.status !== "frozen"; await toggleFreeze(selectedWallet.userId, freeze, freeze ? "Admin-initiated wallet freeze" : "Admin-initiated wallet unfreeze"); setSelectedWallet(null); };

  const columns: Column<WalletEntry>[] = [
    { key: "userName", label: "User", primary: true, render: (row) => { const cfg = ROLE_CONFIG[row.userRole]; const Icon = cfg?.icon || Users; return (<div className="flex items-center gap-2"><div className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0" style={{ background: cfg?.bg }}><Icon className="w-4 h-4" style={{ color: cfg?.color }} /></div><div><p className="text-sm" style={{ color: cn.text }}>{row.userName}</p><p className="text-xs" style={{ color: cn.textSecondary }}>{cfg?.label}</p></div></div>); } },
    { key: "balance", label: "Balance", render: (row) => <span style={{ color: cn.text }}>{formatPoints(row.balance, { compact: true })}</span> },
    { key: "pendingDue", label: "Due", render: (row) => (<span style={{ color: row.pendingDue > 0 ? "#E8A838" : cn.textSecondary }}>{row.pendingDue > 0 ? formatPoints(row.pendingDue) : "\u2013"}</span>) },
    { key: "feePercent", label: "Fee %", hideOnMobile: true, render: (row) => <span style={{ color: cn.textSecondary }}>{row.feePercent}%</span> },
    { key: "status", label: "Status", render: (row) => (<span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs" style={{ background: row.status === "active" ? "#7CE57720" : row.status === "frozen" ? "#3B82F620" : "#EF444420", color: row.status === "active" ? "#5FB865" : row.status === "frozen" ? "#3B82F6" : "#EF4444" }}>{row.status === "frozen" && <Snowflake className="w-3 h-3" />}{row.status}</span>) },
    { key: "actions" as keyof WalletEntry, label: "Actions", hideOnMobile: true, render: (row) => (<button onClick={() => handleSelectWallet(row)} className="flex items-center gap-1 text-xs px-2 py-1 rounded-lg hover:underline cn-touch-target" style={{ color: cn.pink }}><Eye className="w-3 h-3" /> Manage</button>) },
  ];

  const mobileCard = (row: WalletEntry) => { const cfg = ROLE_CONFIG[row.userRole]; const Icon = cfg?.icon || Users; return (<div className="space-y-2" onClick={() => handleSelectWallet(row)}><div className="flex items-center justify-between"><div className="flex items-center gap-2"><div className="w-8 h-8 rounded-lg flex items-center justify-center" style={{ background: cfg?.bg }}><Icon className="w-4 h-4" style={{ color: cfg?.color }} /></div><div><p className="text-sm" style={{ color: cn.text }}>{row.userName}</p><p className="text-xs" style={{ color: cn.textSecondary }}>{cfg?.label}</p></div></div><span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px]" style={{ background: row.status === "active" ? "#7CE57720" : "#3B82F620", color: row.status === "active" ? "#5FB865" : "#3B82F6" }}>{row.status}</span></div><div className="flex items-center justify-between text-xs"><span style={{ color: cn.textSecondary }}>Balance: <span style={{ color: cn.text }}>{formatPoints(row.balance, { compact: true })}</span></span><span style={{ color: row.pendingDue > 0 ? "#E8A838" : cn.textSecondary }}>Due: {row.pendingDue > 0 ? formatPoints(row.pendingDue) : "\u2013"}</span></div><div className="flex items-center justify-between text-xs" style={{ color: cn.textSecondary }}><span>Fee: {row.feePercent}%</span>{row.frozenAmount > 0 && <span style={{ color: "#EF4444" }}>Frozen: {formatPoints(row.frozenAmount)}</span>}<ChevronRight className="w-4 h-4" /></div></div>); };

  return (
    <div className="space-y-6">
      <div><h1 className="text-2xl" style={{ color: cn.text }}><Wallet className="w-6 h-6 inline-block mr-2 -mt-1" />Wallet Management<RealtimeStatusIndicator variant="badge" className="ml-2 align-middle" /></h1><p className="text-sm" style={{ color: cn.textSecondary }}>Manage user wallets, credit/debit points, configure fees</p></div>

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[{ label: "Total Points in Circulation", value: formatPoints(totalBalance, { compact: true }), sub: `\u2248 ${formatBDT(pointsToBDT(totalBalance), { compact: true })}`, icon: Coins, color: "#5FB865", bg: "#7CE57720" }, { label: "Pending Dues (Platform Fees)", value: formatPoints(totalDues, { compact: true }), sub: `${DEFAULT_PLATFORM_FEE_PERCENT}% default`, icon: AlertTriangle, color: "#E8A838", bg: "#FFB54D20" }, { label: "Frozen / Withheld", value: formatPoints(totalFrozen, { compact: true }), sub: `${allWallets.filter(w => w.frozenAmount > 0).length} wallets`, icon: Snowflake, color: "#3B82F6", bg: "#3B82F620" }, { label: "Registration Bonuses Given", value: formatPoints(totalBonusGiven, { compact: true }), sub: `${allWallets.length} users`, icon: Gift, color: "#DB869A", bg: "#FEB4C520" }].map(s => { const Icon = s.icon; return (<div key={s.label} className="cn-stat-card"><div className="w-10 h-10 rounded-xl flex items-center justify-center mb-2" style={{ background: s.bg }}><Icon className="w-5 h-5" style={{ color: s.color }} /></div><p className="text-lg" style={{ color: cn.text }}>{s.value}</p><p className="text-xs" style={{ color: cn.textSecondary }}>{s.label}</p><p className="text-xs mt-0.5" style={{ color: s.color }}>{s.sub}</p></div>); })}</div>

      <div className="finance-card p-5"><div className="flex items-center justify-between mb-3"><h2 className="flex items-center gap-2" style={{ color: cn.text }}><Settings className="w-5 h-5" style={{ color: cn.purple }} />Platform Fee Defaults</h2></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><div className="p-4 rounded-xl" style={{ background: cn.bgInput }}><p className="text-xs" style={{ color: cn.textSecondary }}>Transaction Fee (all parties)</p><p className="text-2xl mt-1" style={{ color: cn.text }}>{DEFAULT_PLATFORM_FEE_PERCENT}%</p><p className="text-xs mt-1" style={{ color: cn.textSecondary }}>Applied to each side of every transaction</p></div><div className="p-4 rounded-xl" style={{ background: cn.bgInput }}><p className="text-xs" style={{ color: cn.textSecondary }}>Default Commission</p><p className="text-2xl mt-1" style={{ color: cn.text }}>{DEFAULT_COMMISSION_PERCENT}%</p><p className="text-xs mt-1" style={{ color: cn.textSecondary }}>Of earnings \u00b7 Configurable per user at approval</p></div><div className="p-4 rounded-xl" style={{ background: cn.bgInput }}><p className="text-xs" style={{ color: cn.textSecondary }}>Point Conversion</p><p className="text-2xl mt-1" style={{ color: cn.text }}>10 CP = \u09F31</p><p className="text-xs mt-1" style={{ color: cn.textSecondary }}>Fixed rate \u00b7 1 BDT = 10 CarePoints</p></div></div></div>

      <div className="finance-card p-5"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-4"><h2 style={{ color: cn.text }}>All Wallets ({allWallets.length})</h2><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4" style={{ color: cn.textSecondary }} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search users..." className="pl-9 pr-4 py-2.5 rounded-xl border text-sm outline-none w-full sm:w-64" style={{ borderColor: cn.border, background: cn.bgInput, color: cn.text }} /></div></div><ResponsiveTable columns={columns} data={wallets} keyExtractor={(row) => row.userId} mobileCard={mobileCard} emptyMessage="No wallets found" /></div>

      {selectedWallet && (<div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-0 sm:p-4" onClick={() => { setSelectedWallet(null); setShowCredit(false); setShowDebit(false); }}><div className="absolute inset-0 bg-black/40" /><div className="relative w-full sm:max-w-lg max-h-[90vh] overflow-y-auto rounded-t-2xl sm:rounded-2xl" style={{ background: cn.bgCard }} onClick={(e) => e.stopPropagation()}><div className="p-5 space-y-4">
        <div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="w-12 h-12 rounded-xl flex items-center justify-center" style={{ background: ROLE_CONFIG[selectedWallet.userRole]?.bg }}>{(() => { const Icon = ROLE_CONFIG[selectedWallet.userRole]?.icon || Users; return <Icon className="w-6 h-6" style={{ color: ROLE_CONFIG[selectedWallet.userRole]?.color }} />; })()}</div><div><p className="text-lg" style={{ color: cn.text }}>{selectedWallet.userName}</p><p className="text-xs" style={{ color: cn.textSecondary }}>{ROLE_CONFIG[selectedWallet.userRole]?.label} \u00b7 {selectedWallet.userId}</p></div></div><button onClick={() => { setSelectedWallet(null); setShowCredit(false); setShowDebit(false); }} className="text-sm cn-touch-target" style={{ color: cn.textSecondary }}>\u2715</button></div>
        <div className="grid grid-cols-2 gap-3"><div className="p-3 rounded-xl" style={{ background: cn.bgInput }}><p className="text-xs" style={{ color: cn.textSecondary }}>Balance</p><p className="text-lg" style={{ color: cn.text }}>{formatPoints(selectedWallet.balance)}</p><p className="text-xs" style={{ color: cn.textSecondary }}>\u2248 {formatBDT(pointsToBDT(selectedWallet.balance))}</p></div><div className="p-3 rounded-xl" style={{ background: selectedWallet.pendingDue > 0 ? "#FFB54D10" : cn.bgInput }}><p className="text-xs" style={{ color: cn.textSecondary }}>Pending Due</p><p className="text-lg" style={{ color: selectedWallet.pendingDue > 0 ? "#E8A838" : cn.text }}>{formatPoints(selectedWallet.pendingDue)}</p><p className="text-xs" style={{ color: cn.textSecondary }}>Platform fee owed</p></div></div>
        <div className="p-3 rounded-xl" style={{ background: cn.purpleBg }}><div className="flex items-center gap-2 mb-2"><Shield className="w-4 h-4" style={{ color: cn.purple }} /><p className="text-sm" style={{ color: cn.purple }}>Fee Configuration</p></div><div className="grid grid-cols-2 gap-3"><div><label className="block text-xs mb-1" style={{ color: cn.textSecondary }}>Transaction Fee (%)</label><input type="number" defaultValue={selectedWallet.feePercent} step="0.5" className="w-full px-3 py-2 rounded-lg border text-sm outline-none" style={{ borderColor: cn.border, background: cn.bgCard, color: cn.text }} /></div><div><label className="block text-xs mb-1" style={{ color: cn.textSecondary }}>Commission (%)</label><input type="number" defaultValue={selectedWallet.commissionPercent} step="1" className="w-full px-3 py-2 rounded-lg border text-sm outline-none" style={{ borderColor: cn.border, background: cn.bgCard, color: cn.text }} /></div></div><button className="mt-2 px-4 py-2 rounded-lg text-xs text-white cn-touch-target" style={{ background: cn.purple }}>Save Fee Config</button></div>
        <div className="space-y-2"><p className="text-sm" style={{ color: cn.text }}>Admin Actions</p>
          <button onClick={() => { setShowCredit(!showCredit); setShowDebit(false); }} className="w-full flex items-center gap-3 p-3 rounded-xl border cn-touch-target" style={{ borderColor: cn.green, background: showCredit ? cn.greenBg : "transparent" }}><Gift className="w-5 h-5" style={{ color: cn.green }} /><div className="flex-1 text-left"><p className="text-sm" style={{ color: cn.text }}>Credit / Donate Points</p><p className="text-xs" style={{ color: cn.textSecondary }}>Give bonus, registration credit, or promo points</p></div></button>
          {showCredit && (<div className="p-3 rounded-xl space-y-2" style={{ background: cn.bgInput }}><input type="number" value={creditAmount} onChange={(e) => setCreditAmount(e.target.value)} placeholder="Amount (CarePoints)" className="w-full px-3 py-2 rounded-lg border text-sm outline-none" style={{ borderColor: cn.border, background: cn.bgCard, color: cn.text }} /><select value={creditReason} onChange={(e) => setCreditReason(e.target.value)} className="w-full px-3 py-2 rounded-lg border text-sm outline-none" style={{ borderColor: cn.border, background: cn.bgCard, color: cn.text }}><option value="">Select reason...</option><option value="registration_bonus">Registration Bonus</option><option value="promo">Promotional Credit</option><option value="refund">Dispute Refund</option><option value="goodwill">Goodwill Gesture</option><option value="compensation">Service Compensation</option><option value="other">Other</option></select><button className="w-full py-2.5 rounded-lg text-white text-sm cn-touch-target" style={{ background: cn.green }} onClick={handleCreditSubmit}><Gift className="w-4 h-4 inline-block mr-1" /> Credit {creditAmount ? formatPoints(parseInt(creditAmount)) : "0 CP"}</button></div>)}
          <button onClick={() => { setShowDebit(!showDebit); setShowCredit(false); }} className="w-full flex items-center gap-3 p-3 rounded-xl border cn-touch-target" style={{ borderColor: "#EF4444", background: showDebit ? "#EF444410" : "transparent" }}><Ban className="w-5 h-5" style={{ color: "#EF4444" }} /><div className="flex-1 text-left"><p className="text-sm" style={{ color: cn.text }}>Withhold / Debit Points</p><p className="text-xs" style={{ color: cn.textSecondary }}>Freeze for payment, due clearance, or other issues</p></div></button>
          {showDebit && (<div className="p-3 rounded-xl space-y-2" style={{ background: cn.bgInput }}><input type="number" value={debitAmount} onChange={(e) => setDebitAmount(e.target.value)} placeholder="Amount (CarePoints)" className="w-full px-3 py-2 rounded-lg border text-sm outline-none" style={{ borderColor: cn.border, background: cn.bgCard, color: cn.text }} /><select value={debitReason} onChange={(e) => setDebitReason(e.target.value)} className="w-full px-3 py-2 rounded-lg border text-sm outline-none" style={{ borderColor: cn.border, background: cn.bgCard, color: cn.text }}><option value="">Select reason...</option><option value="due_clearance">Platform Fee Due Clearance</option><option value="payment_hold">Payment Hold (Dispute)</option><option value="policy_violation">Policy Violation Penalty</option><option value="chargeback">Chargeback</option><option value="fraud">Fraud Prevention Freeze</option><option value="other">Other</option></select><div className="flex gap-2"><button className="flex-1 py-2.5 rounded-lg text-white text-sm cn-touch-target" style={{ background: "#E8A838" }} onClick={() => handleDebitSubmit(true)}><Snowflake className="w-4 h-4 inline-block mr-1" /> Freeze</button><button className="flex-1 py-2.5 rounded-lg text-white text-sm cn-touch-target" style={{ background: "#EF4444" }} onClick={() => handleDebitSubmit(false)}><Ban className="w-4 h-4 inline-block mr-1" /> Debit</button></div></div>)}
          <button className="w-full flex items-center gap-3 p-3 rounded-xl border cn-touch-target" style={{ borderColor: "#3B82F6" }} onClick={handleFreezeToggle}><Snowflake className="w-5 h-5" style={{ color: "#3B82F6" }} /><div className="flex-1 text-left"><p className="text-sm" style={{ color: cn.text }}>{selectedWallet.status === "frozen" ? "Unfreeze Wallet" : "Freeze Entire Wallet"}</p><p className="text-xs" style={{ color: cn.textSecondary }}>{selectedWallet.status === "frozen" ? "Restore full wallet functionality" : "Suspend all transactions for this user"}</p></div></button>
        </div>
        <div><p className="text-sm mb-2" style={{ color: cn.text }}>Recent Transactions</p><div className="space-y-1">{walletTxs.slice(0, 5).map((t) => (<div key={t.id} className="flex items-center justify-between py-2 text-xs"><div className="flex items-center gap-2"><div className="w-6 h-6 rounded-lg flex items-center justify-center" style={{ background: t.amount > 0 ? "#7CE57720" : "#EF444420" }}>{t.amount > 0 ? <ArrowDownRight className="w-3 h-3" style={{ color: "#5FB865" }} /> : <ArrowUpRight className="w-3 h-3" style={{ color: "#EF4444" }} />}</div><span className="truncate max-w-[200px]" style={{ color: cn.textSecondary }}>{t.description}</span></div><span style={{ color: t.amount > 0 ? "#5FB865" : cn.text }}>{t.amount > 0 ? "+" : ""}{formatPoints(t.amount)}</span></div>))}</div></div>
      </div></div></div>)}
    </div>
  );
}