"use client";

import React from "react";
import { FileText, Plus, Search, ArrowLeft, ChevronRight, Edit3, Eye, Trash2, Save, Globe, Layout, Image as ImageIcon, CheckCircle2, Clock, MoreVertical, Settings } from "lucide-react";
import { Button } from "@/frontend/components/ui/button";
import { useNavigate } from "react-router";
import { PageHero } from "@/frontend/components/PageHero";
import { cn } from "@/frontend/theme/tokens";
import { useAsyncData, useDocumentTitle } from "@/frontend/hooks";
import { adminService } from "@/backend/services/admin.service";
import { PageSkeleton } from "@/frontend/components/PageSkeleton";
import { useTranslation } from "react-i18next";

export default function CMSManagerPage() {
  const { t: tDocTitle } = useTranslation("common");
  useDocumentTitle(tDocTitle("pageTitles.cmsManager", "CMS Manager"));

  const navigate = useNavigate();
  const { data, loading } = useAsyncData(() => adminService.getCMSPageData());

  if (loading || !data) return <PageSkeleton />;

  return (
    <div>
      <PageHero gradient="radial-gradient(143.86% 887.35% at -10.97% -22.81%, #1F2937 0%, #111827 100%)" className="pt-8 pb-32 px-6"><div className="max-w-6xl mx-auto"><div className="flex justify-between items-center mb-12"><div className="flex items-center gap-4"><h1 className="text-2xl font-bold text-white">Platform CMS Manager</h1></div><div className="flex gap-2"><Button className="bg-[#FEB4C5] hover:bg-[#DB869A] text-white font-black rounded-xl h-11 px-6 shadow-lg"><Plus className="w-4 h-4 mr-2" /> Create Content</Button><Button className="bg-white/10 hover:bg-white/20 text-white border border-white/20 font-bold rounded-xl h-11 px-6"><Globe className="w-4 h-4 mr-2" /> Purge Global Cache</Button></div></div><div className="grid grid-cols-1 md:grid-cols-4 gap-6">{[{ label: data.stats[0].label, val: data.stats[0].val, icon: Layout }, { label: data.stats[1].label, val: data.stats[1].val, icon: FileText }, { label: data.stats[2].label, val: data.stats[2].val, icon: ImageIcon }, { label: data.stats[3].label, val: data.stats[3].val, icon: Clock }].map((s, i) => (<div key={i} className="finance-card p-6 !bg-white/5 !backdrop-blur-xl !border-white/10 text-white"><s.icon className="w-5 h-5 text-white/40 mb-3" /><p className="text-[10px] font-bold text-white/50 uppercase tracking-widest leading-none mb-2">{s.label}</p><p className="text-2xl font-black">{s.val}</p></div>))}</div></div></PageHero>
      <div className="max-w-6xl mx-auto px-6 -mt-16"><div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-6"><div className="finance-card p-8"><div className="flex flex-col md:flex-row justify-between md:items-center gap-6 mb-10"><h2 className="text-xl font-bold text-gray-800">Recent Content</h2><div className="flex items-center gap-4"><div className="relative w-48"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-300 w-3.5 h-3.5" /><input type="text" placeholder="Filter..." className="w-full h-9 pl-9 pr-3 rounded-lg bg-gray-50 border-none text-[10px] font-bold outline-none" /></div><div className="flex bg-gray-100 rounded-lg p-1">{["All", "Blogs", "Pages"].map(t => (<button key={t} className={`px-4 py-1 rounded-md text-[10px] font-black uppercase transition-all ${t === 'All' ? 'bg-white text-gray-800 shadow-sm' : 'text-gray-400'}`}>{t}</button>))}</div></div></div><div className="space-y-4">{data.content.map((c, i) => (<div key={i} className="p-4 rounded-2xl border border-gray-100 flex items-center justify-between group hover:border-[#FEB4C5] transition-all"><div className="flex items-center gap-4"><div className={`w-10 h-10 rounded-xl flex items-center justify-center ${c.type === 'Blog' ? 'bg-[#FFF5F7] text-[#DB869A]' : 'bg-blue-50 text-blue-500'}`}>{c.type === 'Blog' ? <FileText className="w-5 h-5" /> : <Layout className="w-5 h-5" />}</div><div><p className="text-sm font-bold text-gray-800 leading-none">{c.title}</p><div className="flex items-center gap-3 mt-2"><span className={`text-[10px] font-black uppercase tracking-wider ${c.status === 'Published' ? 'text-[#5FB865]' : c.status === 'Draft' ? 'text-gray-400' : 'text-[#DB869A]'}`}>{c.status}</span><span className="text-[10px] text-gray-300 font-bold">&bull; {c.date}</span></div></div></div><div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="text-gray-200 hover:text-gray-800"><Eye className="w-4 h-4" /></Button><Button variant="ghost" size="icon" className="text-gray-200 hover:text-[#FEB4C5]"><Edit3 className="w-4 h-4" /></Button><Button variant="ghost" size="icon" className="text-gray-200 hover:text-gray-400"><MoreVertical className="w-4 h-4" /></Button></div></div>))}</div><Button variant="ghost" className="w-full mt-8 text-xs font-bold text-gray-400 uppercase tracking-widest">Load More History</Button></div></div>
        <div className="lg:col-span-1 space-y-6"><div className="finance-card p-8 bg-gradient-to-br from-[#FEB4C5]/20 to-[#DB869A]/20 border-[#FEB4C5]/20"><h3 className="font-bold text-gray-800 mb-6 flex items-center gap-2"><Settings className="w-4 h-4 text-[#DB869A]" />Content Settings</h3><div className="space-y-6"><div className="flex items-center justify-between"><span className="text-xs font-bold text-gray-500">Enable Comments</span><div className="w-10 h-6 bg-[#7CE577] rounded-full relative p-1 cursor-pointer"><div className="w-4 h-4 bg-white rounded-full absolute right-1" /></div></div><div className="flex items-center justify-between"><span className="text-xs font-bold text-gray-500">Auto-Index SEO</span><div className="w-10 h-6 bg-[#7CE577] rounded-full relative p-1 cursor-pointer"><div className="w-4 h-4 bg-white rounded-full absolute right-1" /></div></div><div className="flex items-center justify-between"><span className="text-xs font-bold text-gray-500">Social Auto-post</span><div className="w-10 h-6 bg-gray-200 rounded-full relative p-1 cursor-pointer"><div className="w-4 h-4 bg-white rounded-full absolute left-1" /></div></div></div></div><div className="finance-card p-8"><h3 className="font-bold text-gray-800 mb-6">Recent Media</h3><div className="grid grid-cols-3 gap-2">{[1, 2, 3, 4, 5, 6].map(i => (<div key={i} className="aspect-square rounded-xl bg-gray-100 overflow-hidden relative group cursor-pointer"><img src={`https://i.pravatar.cc/100?u=media${i}`} className="w-full h-full object-cover grayscale opacity-60 group-hover:grayscale-0 group-hover:opacity-100 transition-all" alt="media" /></div>))}</div><Button variant="outline" className="w-full mt-6 h-10 rounded-xl border-gray-100 text-[10px] font-black uppercase text-gray-400">Media Library</Button></div></div>
      </div></div>
      <style dangerouslySetInnerHTML={{ __html: ".finance-card { background: rgba(255, 255, 255, 0.95); backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.4); border-radius: 2.5rem; box-shadow: 0 10px 40px rgba(0, 0, 0, 0.03); }" }} />
    </div>
  );
}