import { cn } from "@/frontend/theme/tokens";
import { ArrowLeft, Check, Paperclip, Send, User, ShieldAlert, Clock, AlertCircle } from "lucide-react";
import { useNavigate, useParams } from "react-router";
import { Button } from "@/frontend/components/ui/button";
import { PageHero } from "@/frontend/components/PageHero";
import { useAsyncData, useDocumentTitle } from "@/frontend/hooks";
import { adminService } from "@/backend/services/admin.service";
import { PageSkeleton } from "@/frontend/components/PageSkeleton";
import { useTranslation } from "react-i18next";

export default function SupportTicketDetailPage() {
  const { t: tDocTitle } = useTranslation("common");
  useDocumentTitle(tDocTitle("pageTitles.supportTicketDetail", "Support Ticket Detail"));

  const navigate = useNavigate();
  const { ticketId } = useParams();
  const { data: ticket, loading } = useAsyncData(() => adminService.getSupportTicket(ticketId));

  if (loading || !ticket) return <PageSkeleton />;

  return (
    <div>
      <PageHero gradient="radial-gradient(143.86% 887.35% at -10.97% -22.81%, #1F2937 0%, #111827 100%)" className="pt-8 pb-32 px-6"><div className="max-w-4xl mx-auto"><div className="flex justify-between items-center mb-8"><div className="flex items-center gap-4"><h1 className="text-2xl font-bold text-white">Ticket #TK-90821</h1></div><div className="flex gap-2"><div className="px-4 py-2 rounded-full bg-orange-500 text-white text-[10px] font-black uppercase tracking-widest shadow-lg">Priority: High</div></div></div><div className="finance-card p-6 !bg-white/10 !backdrop-blur-xl !border-white/20 flex items-center justify-between"><div className="flex items-center gap-4 text-white"><div className="w-12 h-12 rounded-2xl bg-[#FEB4C5] flex items-center justify-center font-black">Z</div><div><p className="font-bold text-lg">Payment Dispute - bKash Transfer</p><p className="text-white/70 text-sm">Opened by Zubayer Ahmed \u2022 4h ago</p></div></div><Button className="bg-[#7CE577] hover:bg-[#5FB865] text-white font-bold rounded-xl px-6 h-12">Close Ticket</Button></div></div></PageHero>
      <div className="max-w-4xl mx-auto px-6 -mt-16"><div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-6"><div className="finance-card p-8 min-h-[500px] flex flex-col"><div className="flex-1 space-y-8"><div className="flex gap-4"><div className="w-10 h-10 rounded-full bg-gray-100 flex items-center justify-center font-bold text-gray-400 flex-shrink-0">Z</div><div className="space-y-2 max-w-[80%]"><div className="bg-gray-50 p-4 rounded-2xl rounded-tl-none border border-gray-100"><p className="text-sm text-gray-700">Hello, I made a payment of \u09F33,350 for shift #9921 via bKash but the app still shows it as pending. I have attached the screenshot of the transaction.</p></div><p className="text-[10px] text-gray-300 font-bold ml-1">02:12 PM</p></div></div><div className="flex gap-4 justify-end"><div className="space-y-2 max-w-[80%] text-right"><div className="bg-[#FFF5F7] p-4 rounded-2xl rounded-tr-none border border-[#FEB4C5]/20"><p className="text-sm text-[#DB869A]">Hello Mr. Zubayer, we are checking your transaction with the bKash gateway. Please hold for a few minutes while we verify the TrxID.</p></div><div className="flex items-center justify-end gap-1 mt-1"><p className="text-[10px] text-gray-300 font-bold">02:45 PM</p><Check className="w-3 h-3 text-[#7CE577]" /></div></div><div className="w-10 h-10 rounded-full bg-[#FEB4C5] flex items-center justify-center font-black text-white text-xs flex-shrink-0">A</div></div></div><div className="mt-12 pt-8 border-t border-gray-100"><div className="relative group"><textarea className="w-full p-5 pr-32 rounded-3xl bg-gray-50 border border-gray-100 outline-none focus:ring-2 focus:ring-[#FEB4C5]/20 focus:bg-white transition-all min-h-[120px] text-sm" placeholder="Type your response as an admin..." /><div className="absolute bottom-4 right-4 flex items-center gap-2"><button className="p-3 rounded-2xl bg-white border border-gray-100 text-gray-400 hover:text-[#FEB4C5] transition-colors"><Paperclip className="w-5 h-5" /></button><Button className="h-12 w-12 rounded-2xl bg-[#FEB4C5] hover:bg-[#DB869A] text-white shadow-lg flex items-center justify-center"><Send className="w-5 h-5" /></Button></div></div></div></div></div>
        <div className="lg:col-span-1 space-y-6"><div className="finance-card p-8"><h3 className="font-bold text-gray-800 mb-6 flex items-center gap-2"><User className="w-4 h-4 text-gray-400" />Requester Info</h3><div className="space-y-6"><div className="flex items-center gap-4"><img src="https://i.pravatar.cc/100?u=zubayer" className="w-12 h-12 rounded-2xl object-cover" alt="user" /><div><p className="font-bold text-gray-800 text-sm">Zubayer Ahmed</p><p className="text-[10px] text-[#FEB4C5] font-black uppercase">Guardian</p></div></div><div className="space-y-3 pt-6 border-t border-gray-50"><div className="flex justify-between text-[10px] font-bold"><span className="text-gray-400 uppercase">Trust Level</span><span className="text-[#5FB865]">High (9.2)</span></div><div className="flex justify-between text-[10px] font-bold"><span className="text-gray-400 uppercase">Total Tickets</span><span className="text-gray-800">2</span></div></div><Button variant="ghost" className="w-full text-xs font-bold text-[#FEB4C5] bg-[#FFF5F7] h-10 rounded-xl">Inspect User Profile</Button></div></div><div className="finance-card p-8"><h3 className="font-bold text-gray-800 mb-6">Internal Notes</h3><textarea className="w-full bg-gray-50 border-none rounded-xl p-4 text-xs font-medium text-gray-600 min-h-[100px] outline-none" placeholder="Add a private note for other admins..." /><Button className="w-full mt-4 h-10 bg-gray-900 text-white rounded-xl text-xs font-bold">Save Note</Button></div><div className="finance-card p-6 border-l-4 border-orange-400"><h3 className="text-xs font-bold text-orange-700 mb-3 flex items-center gap-2"><ShieldAlert className="w-4 h-4" /> System Info</h3><div className="space-y-2"><p className="text-[10px] text-gray-500">Browser: Chrome 122.0.x</p><p className="text-[10px] text-gray-500">OS: Windows 11</p><p className="text-[10px] text-gray-500">Language: bn-BD</p></div></div></div>
      </div></div>
      <style dangerouslySetInnerHTML={{ __html: ".finance-card { background: rgba(255, 255, 255, 0.95); backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.4); border-radius: 2.5rem; box-shadow: 0 10px 40px rgba(0, 0, 0, 0.03); }" }} />
    </div>
  );
}