import { cn } from "@/frontend/theme/tokens";
import { Activity, AlertCircle, Ban, CheckCircle, CheckCircle2, CreditCard, History, Lock, Mail, Phone, Shield, ShieldCheck, User } from "lucide-react";
import { useNavigate, useParams } from "react-router";
import { Button } from "@/frontend/components/ui/button";
import { PageHero } from "@/frontend/components/PageHero";
import { useAsyncData, useDocumentTitle } from "@/frontend/hooks";
import { adminService } from "@/backend/services/admin.service";
import { PageSkeleton } from "@/frontend/components/PageSkeleton";
import { useTranslation } from "react-i18next";

export default function UserInspectorPage() {
  const { t: tDocTitle } = useTranslation("common");
  useDocumentTitle(tDocTitle("pageTitles.userInspector", "User Inspector"));

  const navigate = useNavigate();
  const { data: inspectorData, loading } = useAsyncData(() => adminService.getUserInspector());

  if (loading || !inspectorData) return <PageSkeleton />;

  return (
    <div>
      <PageHero gradient="radial-gradient(143.86% 887.35% at -10.97% -22.81%, #1F2937 0%, #111827 100%)" className="pt-8 pb-32 px-6"><div className="max-w-6xl mx-auto"><div className="flex justify-between items-center mb-8"><div className="flex items-center gap-4"><h1 className="text-2xl font-bold text-white">User Inspector</h1></div><div className="flex gap-2"><Button className="bg-red-500 hover:bg-red-600 text-white font-bold rounded-xl h-12 px-6 shadow-lg"><Ban className="w-4 h-4 mr-2" /> Suspend Account</Button><Button className="bg-white/10 hover:bg-white/20 text-white border border-white/20 font-bold rounded-xl h-12 px-6"><Lock className="w-4 h-4 mr-2" /> Reset Security</Button></div></div><div className="finance-card p-6 !bg-white/10 !backdrop-blur-xl !border-white/20 flex flex-col md:flex-row items-center gap-8"><div className="relative"><img src="https://images.unsplash.com/photo-1559839734-2b71f1536783?auto=format&fit=crop&q=80&w=200&h=200" className="w-24 h-24 rounded-3xl object-cover ring-4 ring-white/20" alt="user" /><div className="absolute -bottom-2 -right-2 bg-[#7CE577] text-white p-2 rounded-full border-4 border-[#111827] shadow-lg"><ShieldCheck className="w-4 h-4" /></div></div><div className="flex-1 text-center md:text-left"><div className="flex flex-col md:flex-row items-center gap-3 mb-2"><h2 className="text-3xl font-black text-white">Dr. Rahat Khan</h2><span className="px-3 py-1 rounded-full bg-[#EAB1C1] text-[#DB869A] text-[10px] font-black uppercase tracking-widest">Caregiver</span></div><div className="flex flex-wrap justify-center md:justify-start gap-6 text-white/60 text-sm font-medium"><span className="flex items-center gap-2"><Mail className="w-4 h-4" /> rahat.khan@example.com</span><span className="flex items-center gap-2"><Phone className="w-4 h-4" /> +880 171XXXXXXX</span><span className="flex items-center gap-2 text-[#7CE577]"><Activity className="w-4 h-4" /> Last login: 12m ago</span></div></div><div className="grid grid-cols-2 gap-4 w-full md:w-auto"><div className="p-4 rounded-2xl bg-white/5 border border-white/10 text-center"><p className="text-[10px] text-white/40 uppercase font-bold tracking-widest mb-1">Lifetime Earn</p><p className="text-xl font-black text-white">\u09F32.4M</p></div><div className="p-4 rounded-2xl bg-white/5 border border-white/10 text-center"><p className="text-[10px] text-white/40 uppercase font-bold tracking-widest mb-1">Risk Score</p><p className="text-xl font-black text-[#7CE577]">2%</p></div></div></div></div></PageHero>
      <div className="max-w-6xl mx-auto px-6 -mt-16"><div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-6"><div className="finance-card p-8"><div className="flex justify-between items-center mb-8"><h3 className="text-xl font-bold text-gray-800 flex items-center gap-2"><History className="w-5 h-5 text-gray-400" />Security & Activity Audit</h3><Button variant="ghost" className="text-xs font-bold text-[#FEB4C5]">Export Audit</Button></div><div className="space-y-6 relative before:absolute before:left-5 before:top-2 before:bottom-2 before:w-0.5 before:bg-gray-100">{[{ type: 'login', label: 'Login detected from new device', desc: 'iPhone 15 Pro, Gulshan, Dhaka', time: '12m ago', alert: true }, { type: 'payment', label: 'Payout request processed', desc: '\u09F312,500 transferred to bKash', time: '2h ago' }, { type: 'shift', label: 'Shift started: Evercare Hospital', desc: 'Patient #9021, Ward 4', time: '6h ago' }, { type: 'profile', label: 'NID updated and verified', desc: 'Automated vetting pass (100%)', time: '1d ago' }].map((log, i) => (<div key={i} className="flex gap-6 relative z-10"><div className={`w-10 h-10 rounded-full flex items-center justify-center border-4 border-white shadow-sm ${log.alert ? 'bg-orange-100 text-orange-500' : 'bg-gray-50 text-gray-400'}`}>{log.type === 'login' ? <Lock className="w-4 h-4" /> : log.type === 'payment' ? <CreditCard className="w-4 h-4" /> : <Activity className="w-4 h-4" />}</div><div><p className="font-bold text-gray-800 text-sm">{log.label}</p><p className="text-xs text-gray-400 mt-1">{log.desc}</p><p className="text-[10px] text-gray-300 font-bold mt-2 uppercase">{log.time}</p></div></div>))}</div></div>
          <div className="finance-card p-8"><h3 className="text-xl font-bold text-gray-800 mb-6">Financial Interactions</h3><div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="text-[10px] font-black text-gray-400 uppercase tracking-widest border-b border-gray-100 pb-4"><th className="pb-4">Transaction</th><th className="pb-4">Amount</th><th className="pb-4">Status</th><th className="pb-4 text-right">Date</th></tr></thead><tbody className="divide-y divide-gray-50">{[1, 2, 3].map(i => (<tr key={i} className="text-sm"><td className="py-4 font-bold text-gray-800">Job Payout #8892</td><td className="py-4 font-black text-[#5FB865]">\u09F312,500</td><td className="py-4"><span className="text-[10px] font-bold bg-[#E8F9E7] text-[#5FB865] px-2 py-0.5 rounded uppercase">Success</span></td><td className="py-4 text-right text-gray-400">Mar {15-i}, 2026</td></tr>))}</tbody></table></div></div></div>
        <div className="lg:col-span-1 space-y-6"><div className="finance-card p-8 bg-red-50 border-red-100"><h3 className="font-bold text-red-700 mb-4 flex items-center gap-2"><AlertCircle className="w-5 h-5" />Moderator Action Needed</h3><p className="text-xs text-red-600 leading-relaxed mb-6">User has logged in from 3 distinct IP addresses in the last 24 hours. High risk of account sharing.</p><div className="space-y-3"><Button className="w-full bg-red-600 text-white rounded-xl h-11 font-bold shadow-lg">Lock Financials</Button><Button variant="outline" className="w-full border-red-200 text-red-600 h-11 font-bold">Contact User</Button></div></div><div className="finance-card p-8"><h3 className="font-bold text-gray-800 mb-6">Vetting Status</h3><div className="space-y-4">{[{ label: "NID Verification", ok: true }, { label: "Police Clearance", ok: true }, { label: "Medical License", ok: true }, { label: "Phone Verification", ok: true }, { label: "Psychological Screen", ok: false }].map((v, i) => (<div key={i} className="flex justify-between items-center text-xs"><span className="text-gray-500 font-medium">{v.label}</span>{v.ok ? <CheckCircle2 className="w-4 h-4 text-[#7CE577]" /> : <AlertCircle className="w-4 h-4 text-orange-400" />}</div>))}</div><Button variant="ghost" className="w-full mt-8 text-xs font-bold text-[#FEB4C5] bg-[#FFF5F7] rounded-xl h-11">Manage Verifications</Button></div><div className="finance-card p-8"><h3 className="font-bold text-gray-800 mb-4">Support History</h3><div className="space-y-4"><div className="p-3 rounded-xl bg-gray-50 border border-gray-100 group cursor-pointer hover:border-[#FEB4C5]"><div className="flex justify-between mb-1"><p className="text-[10px] font-bold text-[#DB869A] uppercase">#TK-9921</p><p className="text-[10px] text-gray-300">Resolved</p></div><p className="text-xs font-bold text-gray-700 truncate">Payment delay in bKash transfer</p></div></div></div></div>
      </div></div>
      <style dangerouslySetInnerHTML={{ __html: ".finance-card { background: rgba(255, 255, 255, 0.95); backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.4); border-radius: 3rem; box-shadow: 0 10px 40px rgba(0, 0, 0, 0.03); }" }} />
    </div>
  );
}