"use client";
import React from "react";
import { TrendingUp, ArrowLeft, ChevronRight, ShoppingBag, DollarSign, Users, Star, BarChart3, PieChart as PieChartIcon, ArrowUpRight, ArrowDownRight, Download, Calendar, Filter } from "lucide-react";
import { Button } from "@/frontend/components/ui/button";
import { useNavigate } from "react-router";
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";
import { cn } from "@/frontend/theme/tokens";
import { PageHero } from "@/frontend/components/shared/PageHero";
import { useAsyncData, useDocumentTitle } from "@/frontend/hooks";
import { shopService } from "@/backend/services";
import { PageSkeleton } from "@/frontend/components/shared/PageSkeleton";
import { useTranslation } from "react-i18next";

export default function MerchantAnalyticsPage() {
  const { t: tDocTitle } = useTranslation("common");
  useDocumentTitle(tDocTitle("pageTitles.merchantAnalytics", "Merchant Analytics"));

  const navigate = useNavigate();
  const { data, loading } = useAsyncData(() => shopService.getMerchantAnalyticsData());

  if (loading || !data) return <PageSkeleton cards={3} />;

  return (
    <div>
      <PageHero gradient="radial-gradient(143.86% 887.35% at -10.97% -22.81%, #1F2937 0%, #111827 100%)" className="pt-8 pb-32 px-6"><div className="max-w-6xl mx-auto"><div className="flex justify-between items-center mb-12 text-white"><h1 className="text-2xl font-bold">Sales & Growth Intelligence</h1><div className="flex gap-3"><Button variant="ghost" className="text-white hover:bg-white/10 rounded-xl"><Calendar className="w-4 h-4 mr-2" /> This Week</Button><Button className="bg-[#7CE577] hover:bg-[#5FB865] text-white font-black rounded-xl h-11 px-6 shadow-lg"><Download className="w-4 h-4 mr-2" /> Export Report</Button></div></div><div className="grid grid-cols-1 md:grid-cols-4 gap-6">{[{ label: "Weekly Sales", val: "\u09F3185K", change: "+22%", trend: "up" }, { label: "Total Orders", val: "342", change: "+15%", trend: "up" }, { label: "New Customers", val: "89", change: "+8%", trend: "up" }, { label: "Return Rate", val: "2.1%", change: "-0.3%", trend: "down" }].map((s, i) => (<div key={i} className="finance-card p-6 !bg-white/5 !backdrop-blur-xl !border-white/10 text-white"><p className="text-[10px] font-bold text-white/50 uppercase tracking-widest leading-none mb-2">{s.label}</p><div className="flex items-end gap-3"><p className="text-2xl font-black">{s.val}</p><span className={`text-[10px] font-bold flex items-center mb-1 ${s.trend === 'up' ? 'text-[#7CE577]' : 'text-red-400'}`}>{s.trend === 'up' ? <ArrowUpRight className="w-3 h-3" /> : <ArrowDownRight className="w-3 h-3" />} {s.change}</span></div></div>))}</div></div></PageHero>
      <div className="max-w-6xl mx-auto px-6 -mt-16"><div className="grid grid-cols-1 lg:grid-cols-3 gap-8"><div className="lg:col-span-2 space-y-6"><div className="finance-card p-10"><h3 className="text-xl font-bold text-gray-800 mb-10 flex items-center gap-2"><TrendingUp className="w-5 h-5 text-[#7CE577]" />Daily Sales Velocity</h3><div className="h-80 w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><defs><linearGradient id="colorSalesMerch" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#7CE577" stopOpacity={0.3}/><stop offset="95%" stopColor="#7CE577" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f0f0f0" /><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: '#999' }} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: '#999' }} /><Tooltip /><Area type="monotone" dataKey="sales" stroke="#7CE577" strokeWidth={4} fillOpacity={1} fill="url(#colorSalesMerch)" /></AreaChart></ResponsiveContainer></div></div><div className="finance-card p-10"><h3 className="text-xl font-bold text-gray-800 mb-8">Top Selling SKUs</h3><div className="space-y-6">{[{ name: "Digital BP Monitor", sales: "124 units", pct: 100, color: "bg-[#7CE577]" }, { name: "Pulse Oximeter", sales: "98 units", pct: 79, color: "bg-[#5FB865]" }, { name: "Wheelchair Standard", sales: "42 units", pct: 34, color: "bg-[#FEB4C5]" }].map((p, i) => (<div key={i} className="space-y-2"><div className="flex justify-between items-end"><p className="text-sm font-bold text-gray-800">{p.name}</p><span className="text-sm font-black text-gray-800">{p.sales}</span></div><div className="w-full h-1.5 bg-gray-50 rounded-full overflow-hidden"><div className={`h-full ${p.color}`} style={{ width: `${p.pct}%` }} /></div></div>))}</div></div></div><aside className="lg:col-span-1 space-y-6"><div className="finance-card p-8 bg-gray-900 text-white relative overflow-hidden"><div className="relative z-10"><h3 className="font-bold mb-6 flex items-center gap-2"><Star className="w-4 h-4 text-yellow-400" />Marketing Power</h3><p className="text-xs text-white/50 leading-relaxed mb-8">Visibility is up 15% this week due to the "Nursing Essential" promo.</p><Button className="w-full h-11 bg-white/10 hover:bg-white/20 border border-white/20 rounded-xl text-[10px] font-black uppercase tracking-widest text-white">Join New Campaign</Button></div></div><div className="finance-card p-8"><h3 className="font-bold text-gray-800 mb-6 flex items-center gap-2"><Users className="w-4 h-4 text-gray-400" />Customer Loyalty</h3><div className="text-center py-6"><p className="text-4xl font-black text-[#FEB4C5]">4.9</p><div className="flex gap-1 justify-center mt-2">{[1, 2, 3, 4, 5].map(i => <Star key={i} className="w-3 h-3 text-yellow-400 fill-yellow-400" />)}</div><p className="text-[10px] text-gray-400 font-bold uppercase mt-4">Average Shop Rating</p></div></div></aside></div></div>
      <style dangerouslySetInnerHTML={{ __html: ".finance-card { background: rgba(255, 255, 255, 0.95); backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.4); border-radius: 2.5rem; box-shadow: 0 10px 40px rgba(0, 0, 0, 0.03); }" }} />
    </div>
  );
}