import { useState } from "react";
import { useAsyncData, useDocumentTitle } from "@/frontend/hooks";
import { agencyService } from "@/backend/services/agency.service";
import { PageSkeleton } from "@/frontend/components/PageSkeleton";
import { cn } from "@/frontend/theme/tokens";
import { Settings, Building2, MapPin, Clock, Globe, Phone, Mail, Shield, Bell, CreditCard, Users, FileText, Save, Camera, ChevronRight, CheckCircle2, AlertTriangle, Upload } from "lucide-react";
import { useTranslation } from "react-i18next";

export default function AgencySettingsPage() {
  const { t: tDocTitle } = useTranslation("common");
  useDocumentTitle(tDocTitle("pageTitles.agencySettings", "Agency Settings"));

  const [activeTab, setActiveTab] = useState("profile");
  const { data: settingsData, loading } = useAsyncData(() => agencyService.getAgencySettings());

  if (loading || !settingsData) return <PageSkeleton />;

  const tabs = [{ id: "profile", label: "Agency Profile", icon: Building2 }, { id: "services", label: "Service Areas", icon: MapPin }, { id: "operations", label: "Operations", icon: Clock }, { id: "notifications", label: "Notifications", icon: Bell }, { id: "billing", label: "Billing", icon: CreditCard }, { id: "compliance", label: "Compliance", icon: Shield }];

  return (
    <div className="space-y-5">
      <div><h1 className="text-xl" style={{ color: cn.textHeading }}>Agency Settings</h1><p className="text-sm mt-0.5" style={{ color: cn.textSecondary }}>Manage your agency profile, service areas, and operational settings</p></div>
      <div className="flex gap-2 overflow-x-auto pb-1">{tabs.map(tab => { const Icon = tab.icon; return (<button key={tab.id} onClick={() => setActiveTab(tab.id)} className="flex items-center gap-2 px-3 py-2 rounded-lg text-sm whitespace-nowrap shrink-0" style={{ background: activeTab === tab.id ? "var(--cn-teal-bg)" : "transparent", color: activeTab === tab.id ? "var(--cn-teal)" : cn.textSecondary }}><Icon className="w-4 h-4" />{tab.label}</button>); })}</div>

      {activeTab === "profile" && (<div className="space-y-4"><div className="finance-card p-5 space-y-4"><h3 className="text-sm" style={{ color: cn.text }}>Basic Information</h3><div className="flex items-center gap-4 mb-4"><div className="w-16 h-16 rounded-xl flex items-center justify-center text-white text-xl" style={{ background: "var(--cn-gradient-agency)" }}>HP</div><button className="flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs border" style={{ borderColor: cn.border, color: cn.textSecondary }}><Camera className="w-3 h-3" /> Change Logo</button></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div><label className="text-xs mb-1.5 block" style={{ color: cn.textSecondary }}>Agency Name</label><input type="text" defaultValue="HealthCare Pro BD" className="w-full px-4 py-3 rounded-xl border text-sm" style={{ background: cn.bgInput, borderColor: cn.border, color: cn.text }} /></div><div><label className="text-xs mb-1.5 block" style={{ color: cn.textSecondary }}>Phone</label><input type="tel" defaultValue="+880 1700-000100" className="w-full px-4 py-3 rounded-xl border text-sm" style={{ background: cn.bgInput, borderColor: cn.border, color: cn.text }} /></div><div><label className="text-xs mb-1.5 block" style={{ color: cn.textSecondary }}>Email</label><input type="email" defaultValue="info@healthcareprobd.com" className="w-full px-4 py-3 rounded-xl border text-sm" style={{ background: cn.bgInput, borderColor: cn.border, color: cn.text }} /></div><div><label className="text-xs mb-1.5 block" style={{ color: cn.textSecondary }}>Website</label><input type="url" defaultValue="https://healthcareprobd.com" className="w-full px-4 py-3 rounded-xl border text-sm" style={{ background: cn.bgInput, borderColor: cn.border, color: cn.text }} /></div></div><div><label className="text-xs mb-1.5 block" style={{ color: cn.textSecondary }}>Description</label><textarea rows={3} defaultValue="Leading home healthcare agency in Dhaka." className="w-full px-4 py-3 rounded-xl border text-sm resize-none" style={{ background: cn.bgInput, borderColor: cn.border, color: cn.text }} /></div><button className="flex items-center gap-2 px-5 py-2.5 rounded-xl text-white text-sm" style={{ background: "var(--cn-gradient-agency)" }}><Save className="w-4 h-4" /> Save Changes</button></div></div>)}

      {activeTab === "services" && (<div className="space-y-4"><div className="finance-card p-5 space-y-4"><h3 className="text-sm" style={{ color: cn.text }}>Service Coverage Areas</h3><div className="flex flex-wrap gap-2">{["Gulshan", "Banani", "Dhanmondi", "Uttara", "Mirpur", "Mohammadpur", "Bashundhara", "Badda"].map(area => (<span key={area} className="px-3 py-1.5 rounded-lg text-xs flex items-center gap-1.5" style={{ background: "var(--cn-teal-bg)", color: "var(--cn-teal)" }}><MapPin className="w-3 h-3" /> {area} <button className="ml-1 opacity-50 hover:opacity-100">\u00D7</button></span>))}</div><div className="flex gap-2"><input type="text" placeholder="Add new area..." className="flex-1 px-4 py-2.5 rounded-xl border text-sm" style={{ background: cn.bgInput, borderColor: cn.border, color: cn.text }} /><button className="px-4 py-2.5 rounded-xl text-white text-sm" style={{ background: "var(--cn-gradient-agency)" }}>Add</button></div></div><div className="finance-card p-5 space-y-4"><h3 className="text-sm" style={{ color: cn.text }}>Care Services Offered</h3><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{[{ name: "Elderly Home Care", enabled: true }, { name: "Post-Surgical Recovery", enabled: true }, { name: "Pediatric Care", enabled: true }, { name: "Maternity Care", enabled: false }, { name: "Palliative Care", enabled: false }, { name: "Physiotherapy", enabled: true }].map(service => (<div key={service.name} className="flex items-center justify-between p-3 rounded-xl border" style={{ borderColor: service.enabled ? "var(--cn-teal)" : cn.border }}><span className="text-sm" style={{ color: cn.text }}>{service.name}</span><div className={`w-10 h-6 rounded-full flex items-center px-0.5 cursor-pointer transition-all ${service.enabled ? "justify-end" : "justify-start"}`} style={{ background: service.enabled ? "var(--cn-teal)" : cn.borderLight }}><div className="w-5 h-5 rounded-full bg-white shadow" /></div></div>))}</div></div></div>)}

      {activeTab === "notifications" && (<div className="finance-card p-5 space-y-4"><h3 className="text-sm" style={{ color: cn.text }}>Notification Preferences</h3>{[{ label: "New care requirement matches", desc: "When guardians post requirements matching your service areas", enabled: true }, { label: "Shift alerts", desc: "Late check-ins, missed check-outs", enabled: true }, { label: "Incident reports", desc: "Immediate alerts for incident reports filed", enabled: true }, { label: "Payment notifications", desc: "Invoice payments, payroll processing", enabled: true }, { label: "Platform announcements", desc: "CareNet platform updates", enabled: false }].map((pref, i) => (<div key={i} className="flex items-center justify-between p-3 rounded-xl" style={{ background: cn.bgInput }}><div><p className="text-sm" style={{ color: cn.text }}>{pref.label}</p><p className="text-xs" style={{ color: cn.textSecondary }}>{pref.desc}</p></div><div className={`w-10 h-6 rounded-full flex items-center px-0.5 cursor-pointer transition-all ${pref.enabled ? "justify-end" : "justify-start"}`} style={{ background: pref.enabled ? "var(--cn-teal)" : cn.borderLight }}><div className="w-5 h-5 rounded-full bg-white shadow" /></div></div>))}</div>)}

      {activeTab === "billing" && (<div className="space-y-4"><div className="finance-card p-5 space-y-4"><h3 className="text-sm" style={{ color: cn.text }}>Payment Settings</h3><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div><label className="text-xs mb-1.5 block" style={{ color: cn.textSecondary }}>Default Hourly Rate (BDT)</label><input type="number" defaultValue="350" className="w-full px-4 py-3 rounded-xl border text-sm" style={{ background: cn.bgInput, borderColor: cn.border, color: cn.text }} /></div><div><label className="text-xs mb-1.5 block" style={{ color: cn.textSecondary }}>Invoice Payment Terms</label><select className="w-full px-4 py-3 rounded-xl border text-sm" style={{ background: cn.bgInput, borderColor: cn.border, color: cn.text }}><option>Net 7 days</option><option>Net 15 days</option><option>Net 30 days</option></select></div></div></div><div className="finance-card p-5 space-y-3"><h3 className="text-sm" style={{ color: cn.text }}>Bank Account</h3><div className="p-3 rounded-xl flex items-center gap-3" style={{ background: cn.bgInput }}><CreditCard className="w-5 h-5" style={{ color: "var(--cn-teal)" }} /><div><p className="text-sm" style={{ color: cn.text }}>Dutch Bangla Bank Ltd</p><p className="text-xs" style={{ color: cn.textSecondary }}>Account: ****4521 \u00B7 Banani Branch</p></div><CheckCircle2 className="w-4 h-4 ml-auto" style={{ color: cn.green }} /></div></div></div>)}

      {activeTab === "compliance" && (<div className="space-y-4"><div className="finance-card p-5 space-y-3"><h3 className="text-sm" style={{ color: cn.text }}>Verification Status</h3><div className="p-3 rounded-xl flex items-center gap-3" style={{ background: cn.greenBg }}><CheckCircle2 className="w-5 h-5" style={{ color: cn.green }} /><div><p className="text-sm" style={{ color: cn.green }}>Verified Agency</p><p className="text-xs" style={{ color: cn.textSecondary }}>Last verified: Feb 15, 2026</p></div></div></div><div className="finance-card p-5 space-y-3"><h3 className="text-sm" style={{ color: cn.text }}>Required Documents</h3>{[{ name: "Trade License", status: "valid", expires: "Dec 2026" }, { name: "Tax Identification (TIN)", status: "valid", expires: "N/A" }, { name: "Professional Liability Insurance", status: "valid", expires: "Sep 2026" }, { name: "Staff Background Check Policy", status: "review", expires: "Needs update" }].map((doc, i) => (<div key={i} className="flex items-center justify-between p-3 rounded-xl" style={{ background: cn.bgInput }}><div className="flex items-center gap-3"><FileText className="w-4 h-4" style={{ color: cn.textSecondary }} /><div><p className="text-sm" style={{ color: cn.text }}>{doc.name}</p><p className="text-xs" style={{ color: cn.textSecondary }}>Expires: {doc.expires}</p></div></div><span className="px-2 py-0.5 rounded-full text-xs" style={{ background: doc.status === "valid" ? cn.greenBg : cn.amberBg, color: doc.status === "valid" ? cn.green : cn.amber }}>{doc.status === "valid" ? "Valid" : "Needs Review"}</span></div>))}<button className="flex items-center gap-2 px-4 py-2.5 rounded-xl border text-sm" style={{ borderColor: cn.border, color: cn.textSecondary }}><Upload className="w-4 h-4" /> Upload Document</button></div></div>)}

      {activeTab === "operations" && (<div className="space-y-4"><div className="finance-card p-5 space-y-4"><h3 className="text-sm" style={{ color: cn.text }}>Operating Hours</h3><div className="space-y-2">{["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"].map(day => (<div key={day} className="flex items-center gap-3 p-3 rounded-xl" style={{ background: cn.bgInput }}><span className="text-sm w-24" style={{ color: cn.text }}>{day}</span><input type="time" defaultValue="08:00" className="px-2 py-1.5 rounded-lg border text-sm" style={{ background: cn.bgCard, borderColor: cn.border, color: cn.text }} /><span style={{ color: cn.textSecondary }}>to</span><input type="time" defaultValue="22:00" className="px-2 py-1.5 rounded-lg border text-sm" style={{ background: cn.bgCard, borderColor: cn.border, color: cn.text }} /></div>))}</div></div><div className="finance-card p-5 space-y-4"><h3 className="text-sm" style={{ color: cn.text }}>Shift Configuration</h3><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div><label className="text-xs mb-1.5 block" style={{ color: cn.textSecondary }}>Default Shift Duration</label><select className="w-full px-4 py-3 rounded-xl border text-sm" style={{ background: cn.bgInput, borderColor: cn.border, color: cn.text }}><option>8 hours</option><option>12 hours</option></select></div><div><label className="text-xs mb-1.5 block" style={{ color: cn.textSecondary }}>Late Tolerance (minutes)</label><input type="number" defaultValue="15" className="w-full px-4 py-3 rounded-xl border text-sm" style={{ background: cn.bgInput, borderColor: cn.border, color: cn.text }} /></div></div></div></div>)}
    </div>
  );
}