import { useState } from "react";
import { cn } from "@/frontend/theme/tokens";
import { Wallet, Users, TrendingUp, Clock, Download, CheckCircle2, CreditCard, ArrowRight, Building2, Calendar, AlertCircle } from "lucide-react";
import { formatBDT } from "@/backend/utils/currency";
import { PaymentMethodSelector } from "@/frontend/components/shared/PaymentMethodSelector";
import { useTranslation } from "react-i18next";
import { useAsyncData, useDocumentTitle } from "@/frontend/hooks";
import { agencyService } from "@/backend/services/agency.service";
import { PageSkeleton } from "@/frontend/components/PageSkeleton";
import type { CaregiverPayout, PayoutStatus } from "@/backend/models";

const payoutStatusConfig: Record<PayoutStatus, { label: string; color: string; bg: string }> = { pending: { label: "Pending", color: "#E8A838", bg: "rgba(232,168,56,0.12)" }, processing: { label: "Processing", color: "#0288D1", bg: "rgba(2,136,209,0.12)" }, paid: { label: "Paid", color: "#5FB865", bg: "rgba(95,184,101,0.12)" } };
const methodColors: Record<string, string> = { bKash: "#D12053", Nagad: "#ED6E1B", Rocket: "#8E24AA", "Bank Transfer": "#37474F" };

export default function AgencyPayrollPage() {
  const { t: tDocTitle } = useTranslation("common");
  useDocumentTitle(tDocTitle("pageTitles.agencyPayroll", "Agency Payroll"));

  const { i18n } = useTranslation();
  const isBangla = i18n.language === "bn";
  const bdtOpts = { bangla: isBangla };
  const [period, setPeriod] = useState("mar-1-15");
  const [paymentOpen, setPaymentOpen] = useState(false);
  const [payingCaregiver, setPayingCaregiver] = useState<CaregiverPayout | null>(null);

  const { data: payrollData, loading } = useAsyncData(() => agencyService.getPayrollData());

  if (loading || !payrollData) return <PageSkeleton cards={4} />;

  const { payouts: caregiverPayouts, history: payoutHistory, settlements: settlementPeriods } = payrollData;
  const totalReceived = 156000; const totalPayouts = 94200; const agencyRevenue = totalReceived - totalPayouts;
  const pendingPayouts = caregiverPayouts.filter((p) => p.status === "pending").reduce((s, p) => s + p.net, 0);
  const handlePayCaregiver = (caregiver: CaregiverPayout) => { setPayingCaregiver(caregiver); setPaymentOpen(true); };

  return (
    <>
      <div className="space-y-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{ background: cn.tealBg }}><Wallet className="w-5 h-5" style={{ color: cn.teal }} /></div><div><h1 className="text-xl" style={{ color: cn.text }}>Payroll & Payouts</h1><p className="text-sm" style={{ color: cn.textSecondary }}>Manage caregiver payments and agency revenue</p></div></div><select value={period} onChange={(e) => setPeriod(e.target.value)} className="px-4 py-2 rounded-xl border text-sm" style={{ background: cn.bgInput, borderColor: cn.border, color: cn.text }}><option value="mar-1-15">March 1-15, 2026</option><option value="feb-16-28">February 16-28, 2026</option></select></div>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">{[{ label: "Received from Guardians", value: formatBDT(totalReceived, { ...bdtOpts, compact: true }), icon: CreditCard, color: cn.teal, bg: cn.tealBg }, { label: "Caregiver Payouts", value: formatBDT(totalPayouts, { ...bdtOpts, compact: true }), icon: Users, color: cn.pink, bg: cn.pinkBg }, { label: "Agency Revenue", value: formatBDT(agencyRevenue, { ...bdtOpts, compact: true }), icon: TrendingUp, color: cn.green, bg: cn.greenBg }, { label: "Pending Payouts", value: formatBDT(pendingPayouts, { ...bdtOpts, compact: true }), icon: Clock, color: cn.amber, bg: cn.amberBg }].map((s) => { const Icon = s.icon; return (<div key={s.label} className="finance-card p-4"><Icon className="w-5 h-5 mb-2" style={{ color: s.color }} /><p className="text-lg" style={{ color: s.color }}>{s.value}</p><p className="text-xs" style={{ color: cn.textSecondary }}>{s.label}</p></div>); })}</div>
        <div className="finance-card p-5"><div className="flex items-center gap-2 mb-4"><Calendar className="w-4 h-4" style={{ color: cn.teal }} /><h3 className="text-sm" style={{ color: cn.text }}>Settlement Periods</h3></div><div className="space-y-2">{settlementPeriods.map((sp) => (<div key={sp.period} className="flex items-center justify-between p-3 rounded-xl" style={{ background: cn.bgInput }}><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-lg flex items-center justify-center" style={{ background: sp.status === "active" ? cn.amberBg : cn.greenBg }}>{sp.status === "active" ? <Clock className="w-4 h-4" style={{ color: cn.amber }} /> : <CheckCircle2 className="w-4 h-4" style={{ color: cn.green }} />}</div><div><p className="text-sm" style={{ color: cn.text }}>{sp.period}</p><p className="text-xs" style={{ color: cn.textSecondary }}>Received: {formatBDT(sp.received, bdtOpts)} \u00B7 Paid: {formatBDT(sp.paid, bdtOpts)}</p></div></div><div className="text-right"><span className="px-2 py-0.5 rounded-full text-[10px]" style={{ background: sp.status === "active" ? cn.amberBg : cn.greenBg, color: sp.status === "active" ? cn.amber : cn.green }}>{sp.status === "active" ? "Active" : "Settled"}</span>{sp.pending > 0 && <p className="text-xs mt-0.5" style={{ color: cn.amber }}>{formatBDT(sp.pending, bdtOpts)} pending</p>}</div></div>))}</div></div>
        <div className="finance-card p-5"><h3 className="text-sm mb-3" style={{ color: cn.text }}>Revenue Split</h3><div className="flex h-6 rounded-full overflow-hidden mb-3"><div style={{ width: `${(totalPayouts / totalReceived) * 100}%`, background: cn.pink }} /><div style={{ width: `${(agencyRevenue / totalReceived) * 100}%`, background: cn.green }} /></div><div className="flex justify-between text-xs" style={{ color: cn.textSecondary }}><span className="flex items-center gap-1"><span className="w-2.5 h-2.5 rounded-full" style={{ background: cn.pink }} /> Caregiver Payouts</span><span className="flex items-center gap-1"><span className="w-2.5 h-2.5 rounded-full" style={{ background: cn.green }} /> Agency Margin</span></div></div>
        <div className="finance-card p-5"><div className="flex items-center justify-between mb-4"><h3 className="text-sm" style={{ color: cn.text }}>Caregiver Payouts</h3><div className="flex gap-2"><button className="px-3 py-1.5 rounded-lg text-xs text-white cn-touch-target" style={{ background: "var(--cn-gradient-agency)" }}>Process All Pending</button><button className="px-3 py-1.5 rounded-lg text-xs border flex items-center gap-1 cn-touch-target" style={{ borderColor: cn.border, color: cn.textSecondary }}><Download className="w-3 h-3" /> Export</button></div></div><div className="overflow-x-auto"><table className="w-full text-xs min-w-[750px]"><thead><tr style={{ color: cn.textSecondary, borderBottom: `1px solid ${cn.border}` }}><th className="text-left py-2 px-2">Caregiver</th><th className="text-left py-2 px-2">Shifts</th><th className="text-left py-2 px-2">Rate</th><th className="text-left py-2 px-2">Net</th><th className="text-left py-2 px-2">Method</th><th className="text-left py-2 px-2">Status</th><th className="text-left py-2 px-2">Action</th></tr></thead><tbody>{caregiverPayouts.map((p) => { const st = payoutStatusConfig[p.status]; const mColor = methodColors[p.method] || cn.textSecondary; return (<tr key={p.name} style={{ borderBottom: `1px solid ${cn.border}` }}><td className="py-2.5 px-2"><div className="flex items-center gap-2"><div className="w-7 h-7 rounded-full flex items-center justify-center text-[10px]" style={{ background: cn.pinkBg, color: cn.pink }}>{p.name.split(" ").map(w => w[0]).join("")}</div><span style={{ color: cn.text }}>{p.name}</span></div></td><td className="py-2.5 px-2" style={{ color: cn.textSecondary }}>{p.shifts}</td><td className="py-2.5 px-2" style={{ color: cn.textSecondary }}>{formatBDT(p.rate, bdtOpts)}</td><td className="py-2.5 px-2" style={{ color: cn.green }}>{formatBDT(p.net, bdtOpts)}</td><td className="py-2.5 px-2"><span style={{ color: mColor }}>{p.method}</span></td><td className="py-2.5 px-2"><span className="px-2 py-0.5 rounded-full" style={{ background: st.bg, color: st.color }}>{st.label}</span></td><td className="py-2.5 px-2">{p.status === "pending" && <button onClick={() => handlePayCaregiver(p)} className="px-2.5 py-1 rounded text-xs cn-touch-target flex items-center gap-1" style={{ background: cn.tealBg, color: cn.teal }}>Pay <ArrowRight className="w-3 h-3" /></button>}</td></tr>); })}</tbody></table></div></div>
        <div className="finance-card p-5"><h3 className="text-sm mb-3" style={{ color: cn.text }}>Recent Payout History</h3><div className="space-y-2">{payoutHistory.map((h) => (<div key={h.ref} className="flex items-center gap-3 p-3 rounded-xl" style={{ background: cn.bgInput }}><CheckCircle2 className="w-4 h-4 shrink-0" style={{ color: cn.green }} /><div className="flex-1 min-w-0"><p className="text-sm" style={{ color: cn.text }}>{h.caregiver} \u2014 {formatBDT(h.amount, bdtOpts)}</p><div className="flex items-center gap-2 flex-wrap"><p className="text-xs" style={{ color: cn.textSecondary }}>{h.date}</p><span className="inline-flex items-center gap-1 text-xs px-1.5 py-0.5 rounded" style={{ background: `${h.methodColor}10`, color: h.methodColor }}><span className="w-1.5 h-1.5 rounded-full" style={{ background: h.methodColor }} />{h.method}</span><p className="text-xs" style={{ color: cn.textSecondary }}>{h.ref}</p></div></div></div>))}</div></div>
      </div>
      <PaymentMethodSelector open={paymentOpen} onClose={() => { setPaymentOpen(false); setPayingCaregiver(null); }} amount={payingCaregiver?.net || 0} invoiceRef={payingCaregiver ? `Payout: ${payingCaregiver.name}` : undefined} onPaymentComplete={() => { setPaymentOpen(false); setPayingCaregiver(null); }} />
    </>
  );
}